import type { ToolCatalog, ToolDefinition } from './types.js';

export function renderMarkdown(catalog: ToolCatalog): string {
  const anchors = uniqueAnchors(catalog.tools.map((tool) => tool.name));
  const lines: string[] = [
    '# Tool Catalog',
    '',
    `Generated by toolmirror from ${catalog.tools.length} tool definition${catalog.tools.length === 1 ? '' : 's'}.`,
    '',
    '## Index',
    ''
  ];

  for (const [index, tool] of catalog.tools.entries()) {
    lines.push(`- [${escapeMarkdown(tool.name)}](#${anchors[index]}) - ${tool.risk.level}`);
  }

  lines.push('');

  for (const [index, tool] of catalog.tools.entries()) {
    renderTool(lines, tool, anchors[index]);
  }

  return `${lines.join('\n')}\n`;
}

function renderTool(lines: string[], tool: ToolDefinition, anchor: string): void {
  lines.push(`<h2 id="${anchor}">${escapeHtml(tool.name)}</h2>`, '');
  if (tool.description) {
    lines.push(tool.description, '');
  }

  lines.push(`- Source: \`${tool.source}\``);
  lines.push(`- Risk: **${tool.risk.level}**`);
  lines.push(`- Risk reasons: ${tool.risk.reasons.map(escapeMarkdown).join('; ')}`);
  lines.push('');

  lines.push('| Parameter | Type | Required | Description |');
  lines.push('| --- | --- | --- | --- |');
  if (tool.parameters.length === 0) {
    lines.push('| _none_ |  |  |  |');
  } else {
    for (const parameter of tool.parameters) {
      lines.push(`| \`${escapePipes(parameter.name)}\` | ${escapePipes(parameter.type)} | ${parameter.required ? 'yes' : 'no'} | ${escapePipes(parameter.description)} |`);
    }
  }
  lines.push('');
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function uniqueAnchors(names: string[]): string[] {
  const counts = new Map<string, number>();

  return names.map((name) => {
    const base = slug(name) || 'tool';
    const count = (counts.get(base) ?? 0) + 1;
    counts.set(base, count);
    return count === 1 ? base : `${base}-${count}`;
  });
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeMarkdown(value: string): string {
  return value.replace(/([*_`[\]])/g, '\\$1');
}

function escapePipes(value: string): string {
  return escapeMarkdown(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
