import type { ToolCatalog, ToolDefinition } from './types.js';

export function renderMarkdown(catalog: ToolCatalog): string {
  const lines: string[] = [
    '# Tool Catalog',
    '',
    `Generated by toolmirror from ${catalog.tools.length} tool definition${catalog.tools.length === 1 ? '' : 's'}.`,
    '',
    '## Index',
    ''
  ];

  for (const tool of catalog.tools) {
    lines.push(`- [${escapeMarkdown(tool.name)}](#${slug(tool.name)}) - ${tool.risk.level}`);
  }

  lines.push('');

  for (const tool of catalog.tools) {
    renderTool(lines, tool);
  }

  return `${lines.join('\n')}\n`;
}

function renderTool(lines: string[], tool: ToolDefinition): void {
  lines.push(`## ${escapeMarkdown(tool.name)}`, '');
  if (tool.description) {
    lines.push(tool.description, '');
  }

  lines.push(`- Source: \`${tool.source}\``);
  lines.push(`- Risk: **${tool.risk.level}**`);
  lines.push(`- Risk reasons: ${tool.risk.reasons.map(escapeMarkdown).join('; ')}`);
  lines.push('');

  lines.push('| Parameter | Type | Required | Description |');
  lines.push('| --- | --- | --- | --- |');
  if (tool.parameters.length === 0) {
    lines.push('| _none_ |  |  |  |');
  } else {
    for (const parameter of tool.parameters) {
      lines.push(`| \`${escapePipes(parameter.name)}\` | ${escapePipes(parameter.type)} | ${parameter.required ? 'yes' : 'no'} | ${escapePipes(parameter.description)} |`);
    }
  }
  lines.push('');
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function escapeMarkdown(value: string): string {
  return value.replace(/([*_`[\]])/g, '\\$1');
}

function escapePipes(value: string): string {
  return escapeMarkdown(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
